# Models to compare
MODELS:
  - NAME: "distilbert-base-uncased"
    ALIAS: "distilbert"
  - NAME: "bert-base-uncased"
    ALIAS: "bert"  
  - NAME: "roberta-base"
    ALIAS: "roberta"
  - NAME: "microsoft/deberta-v3-base"
    ALIAS: "deberta"

# Labels
NUM_LABELS: 6
LABELS:
  - "joy"
  - "sadness"
  - "anger"
  - "love"
  - "surprise"
  - "neutral"

LABEL_MAP:
  happiness: "joy"
  enthusiasm: "joy"
  fun: "joy"
  relief: "joy"
  love: "love"
  sadness: "sadness"
  empty: "sadness"
  anger: "anger"
  hate: "anger"
  neutral: "neutral"
  surprise: "surprise"

# Data + split
DATA:
  CSV_PATH: "C:/Users/Korisnik/Desktop/Faks/nlp/projekt/archive/final_dataset.csv"

  TEXT_COL: "text"
  LABEL_COL: "emotion"
  VALID_SIZE: 0.1               # 10% valid
  STRATIFY: false                # koristi stratify_by_column="labels"
  SEED: 42
  OUTPUT_ROOT: "outputs"

# Training configuration
TRAINING:
  LEARNING_RATE: 2e-5
  BATCH_SIZE: 16
  NUM_EPOCHS: 5
  WEIGHT_DECAY: 0.01
  EVAL_STRATEGY: "epoch"        # Trainer evaluacija po epohi [web:136]
  SAVE_STRATEGY: "epoch"
  BEST_MODEL_METRIC: "f1"

# Model versioning
VERSIONING:
  ENABLED: true
  MLFLOW_TRACKING_URI: "./mlruns"
  EXPERIMENT_NAME: "emotion_classification2"
